blank_issues_enabled: true
contact_links:
  - name: Community development and test coordination
    url: https://discord.gg/5NKHAA8Wb3
    about: Coordinate alpha tests and discuss implementation in events-dev.
